// quizzes-bio/topic-5-2.js
// Unit 5: Heredity — Topic 5.2: Meiosis and Genetic Diversity
// Registered in quizzes-bio/index.js as "bio-topic-5-2".
window.QUIZ_QUESTIONS = [
  {
    id: "5.2-1",
    question: "Crossing over during prophase I directly contributes to genetic diversity by:",
    options: ["Duplicating an entire chromosome set", "Swapping DNA between homologous chromatids", "Preventing any genetic recombination", "Doubling the total number of chromosomes"],
    correctIndex: 1,
    explanation: "Crossing over swaps segments between non-sister chromatids of homologous chromosomes, producing recombinant chromosomes with new combinations of alleles not present in either parent chromosome."
  },
  {
    id: "5.2-2",
    question: "Independent assortment during meiosis I refers to:",
    options: ["Random orientation of each homologous pair", "The pairing of sister chromatids only", "A process exclusive to mitosis alone", "The exchange of DNA between chromatids"],
    correctIndex: 0,
    explanation: "Independent assortment means each pair of homologous chromosomes aligns randomly at the metaphase plate during meiosis I, independent of how other homologous pairs align, generating many possible combinations of maternal and paternal chromosomes in gametes."
  },
  {
    id: "5.2-3",
    question: "For an organism with n = 23 (as in humans), independent assortment alone can generate how many possible chromosome combinations in gametes?",
    options: ["23 combinations", "46 combinations", "2^23 (over 8 million)", "23 squared combinations"],
    correctIndex: 2,
    explanation: "With 23 pairs of chromosomes, each pair assorting independently into gametes, there are 2^23 (more than 8 million) possible combinations of maternal and paternal chromosomes in the resulting gametes."
  },
  {
    id: "5.2-4",
    question: "Which of the following contributes to genetic diversity but does NOT occur during mitosis?",
    options: ["Replication of the DNA", "Cytokinesis of cytoplasm", "Crossing over of homologs", "Chromosome condensation"],
    correctIndex: 2,
    explanation: "Crossing over specifically occurs between homologous chromosomes during meiotic prophase I; mitosis does not involve pairing of homologs or exchange of genetic material between them."
  },
  {
    id: "5.2-5",
    question: "Random fertilization further increases genetic diversity in sexually reproducing organisms because:",
    options: ["Any unique sperm can fertilize any unique egg", "All sperm and eggs are genetically identical", "Fertilization always joins the same gametes", "Only one offspring genotype can result"],
    correctIndex: 0,
    explanation: "Because independent assortment and crossing over create enormous gamete diversity in both parents, the essentially random pairing of any sperm with any egg during fertilization multiplies the potential genetic combinations even further."
  },
  {
    id: "5.2-6",
    question: "A tetrad, formed during prophase I of meiosis, consists of:",
    options: ["A single chromosome with two chromatids", "Two homologs with four chromatids", "Four separate, unrelated chromosomes", "A single unreplicated chromosome"],
    correctIndex: 1,
    explanation: "A tetrad forms when a pair of homologous chromosomes (each already replicated into two sister chromatids) come together during synapsis, resulting in a structure of four chromatids total."
  },
  {
    id: "5.2-7",
    question: "Which statement correctly compares crossing over and independent assortment as sources of genetic variation?",
    options: ["It shuffles alleles within one chromosome pair", "They are the same process with different names", "Independent assortment is only asexual", "Crossing over increases chromosome number"],
    correctIndex: 0,
    explanation: "Crossing over recombines alleles located on the same pair of homologous chromosomes, while independent assortment determines how different chromosome pairs are distributed to gametes relative to one another — both are distinct mechanisms generating diversity."
  },
  {
    id: "5.2-8",
    question: "A gamete containing a chromosome with a mix of maternal and paternal DNA segments (due to a crossover event) is called a:",
    options: ["Homologous chromosome", "Recombinant chromosome", "Sister chromatid", "Autosome only"],
    correctIndex: 1,
    explanation: "When crossing over exchanges DNA between maternal and paternal homologs, the resulting chromosome — carrying a mix of both — is called a recombinant chromosome."
  },
  {
    id: "5.2-9",
    question: "Why is genetic diversity generated by meiosis considered evolutionarily important?",
    options: ["It makes all offspring identical to parents", "It supplies variation for natural selection", "It prevents adaptation to new environments", "It has no connection to evolution at all"],
    correctIndex: 1,
    explanation: "The genetic variation produced by crossing over, independent assortment, and random fertilization gives populations a range of traits; natural selection can then favor those traits best suited to the current environment, driving evolutionary change."
  },
  {
    id: "5.2-10",
    question: "If crossing over did not occur at all during meiosis, what would be the most direct consequence for genetic diversity?",
    options: ["Genetic diversity would increase dramatically", "Gametes would carry unshuffled chromosomes", "All organisms would become identical clones", "Meiosis would be unable to occur at all"],
    correctIndex: 1,
    explanation: "Without crossing over, each chromosome would be inherited as an intact unit from one parent, reducing genetic variation compared to normal meiosis, although independent assortment would still shuffle whole chromosomes."
  },
];
