// AP Environmental Science — Unit 9 (Global Change)
// Registered in quizzes-apes/index.js as "apes-topic-9-2".
// Topic 9.2 — Reducing Ozone Depletion

window.QUIZ_QUESTIONS = [
  {
    id: "9-2-1",
    question: "The Montreal Protocol is an international agreement that",
    options: [
      "restricts persistent organic pollutants worldwide",
      "limits greenhouse gas emissions among signatory nations",
      "phases out production of ozone depleting substances",
      "regulates international trade in endangered species"
    ],
    correctIndex: 2,
    explanation: "Adopted in 1987, it is often called the most successful environmental treaty. Every United Nations member state has ratified it."
  },
  {
    id: "9-2-2",
    question: "The Montreal Protocol succeeded in part because",
    options: [
      "only a handful of countries needed to participate",
      "the costs of compliance fell entirely on consumers",
      "ozone depletion required no changes to industry",
      "substitutes existed and the problem was narrowly defined"
    ],
    correctIndex: 3,
    explanation: "A limited set of chemicals with available replacements made agreement tractable. Climate change is harder because fossil fuels pervade the entire economy."
  },
  {
    id: "9-2-3",
    question: "Hydrochlorofluorocarbons were adopted as interim CFC replacements because they",
    options: [
      "break down more readily before reaching the stratosphere",
      "are entirely harmless to the global climate system",
      "cost substantially more than the CFCs they replaced",
      "contain no chlorine and cannot affect ozone at all"
    ],
    correctIndex: 0,
    explanation: "Shorter atmospheric lifetimes mean less chlorine reaches the ozone layer. HCFCs still deplete ozone somewhat and are themselves being phased out."
  },
  {
    id: "9-2-4",
    question: "Hydrofluorocarbons replaced HCFCs but created a new problem because HFCs",
    options: [
      "destroy stratospheric ozone even more rapidly",
      "are potent greenhouse gases contributing to warming",
      "are acutely toxic to humans at low concentrations",
      "cannot be used in any refrigeration application"
    ],
    correctIndex: 1,
    explanation: "HFCs contain no chlorine and spare the ozone layer entirely. The Kigali Amendment now phases them down for climate reasons."
  },
  {
    id: "9-2-5",
    question: "The Kigali Amendment to the Montreal Protocol addresses",
    options: [
      "monitoring of stratospheric ozone concentrations",
      "the remaining production of chlorofluorocarbons",
      "phasing down hydrofluorocarbons to limit warming",
      "compensation for countries affected by ozone loss"
    ],
    correctIndex: 2,
    explanation: "It extended an ozone treaty to address a purely climate concern. Full implementation could avoid several tenths of a degree of warming."
  },
  {
    id: "9-2-6",
    question: "The Montreal Protocol included a multilateral fund in order to",
    options: [
      "finance research into new ozone depleting compounds",
      "pay for satellite monitoring of the ozone layer",
      "compensate chemical manufacturers for lost revenue",
      "help developing countries transition to alternatives"
    ],
    correctIndex: 3,
    explanation: "Differentiated timelines and financial support secured broad participation. This design has been studied as a model for other treaties."
  },
  {
    id: "9-2-7",
    question: "The stratospheric ozone layer is currently",
    options: [
      "showing signs of recovery expected to continue for decades",
      "fully recovered to its preindustrial condition already",
      "unchanged since measurements first began in the 1970s",
      "continuing to thin at an accelerating annual rate"
    ],
    correctIndex: 0,
    explanation: "The Antarctic hole has begun shrinking as chlorine levels decline. Full recovery is projected around the middle of this century."
  },
  {
    id: "9-2-8",
    question: "Recovery of the ozone layer takes decades even after emissions stop because CFCs",
    options: [
      "continue to be produced in large quantities illegally",
      "persist in the atmosphere for many decades",
      "are continuously generated by natural processes",
      "break down immediately upon release into the air"
    ],
    correctIndex: 1,
    explanation: "Atmospheric lifetimes range from roughly 50 to over 100 years. Chlorine already aloft continues destroying ozone regardless of new emissions."
  },
  {
    id: "9-2-9",
    question: "Detection of unexpected CFC-11 emissions after 2013 demonstrated that",
    options: [
      "ozone depletion had already been fully reversed",
      "the Montreal Protocol had no measurable effect",
      "monitoring and enforcement remain necessary",
      "CFCs are produced naturally in large quantities"
    ],
    correctIndex: 2,
    explanation: "Atmospheric measurements traced the source to unreported production in eastern Asia. Emissions declined again after the finding was publicized."
  },
  {
    id: "9-2-10",
    question: "The Montreal Protocol is often contrasted with climate agreements because ozone depletion",
    options: [
      "required no international cooperation to address",
      "produced benefits only for a small number of countries",
      "affected far more sectors of the global economy",
      "involved fewer industries with ready substitutes available"
    ],
    correctIndex: 3,
    explanation: "A narrow problem with cheap alternatives is far easier to negotiate. Carbon emissions come from nearly every economic activity."
  }
];
