// AP Environmental Science — Unit 6 (Energy Resources and Consumption)
// Registered in quizzes-apes/index.js as "apes-topic-6-10".
// Topic 6.10 — Geothermal Energy

window.QUIZ_QUESTIONS = [
  {
    id: "6-10-1",
    question: "Geothermal energy originates from",
    options: [
      "heat within Earth from radioactive decay and formation",
      "friction generated by ocean currents along coasts",
      "chemical reactions occurring in surface groundwater",
      "sunlight absorbed by the upper layers of soil"
    ],
    correctIndex: 0,
    explanation: "Radioactive decay in the mantle and residual formation heat supply the energy. This makes geothermal independent of weather and time of day."
  },
  {
    id: "6-10-2",
    question: "Commercial geothermal electricity generation is concentrated in regions",
    options: [
      "located in the stable interiors of ancient continents",
      "near plate boundaries where heat is close to the surface",
      "with the thickest continental crust found on Earth",
      "at the highest latitudes with permanently frozen ground"
    ],
    correctIndex: 1,
    explanation: "Iceland, the Philippines, and California's Geysers field all sit in such settings. Elsewhere, drilling to usable temperatures is prohibitively expensive."
  },
  {
    id: "6-10-3",
    question: "Geothermal power plants generate electricity by",
    options: [
      "capturing sunlight concentrated by mirror arrays",
      "burning underground methane released by hot rock",
      "using steam or hot water to drive turbines",
      "converting underground heat directly into current"
    ],
    correctIndex: 2,
    explanation: "Flash and binary cycle plants both ultimately spin a turbine. Binary systems transfer heat to a secondary fluid with a lower boiling point."
  },
  {
    id: "6-10-4",
    question: "Ground source heat pumps differ from geothermal power plants in that heat pumps",
    options: [
      "require locations near active volcanic activity",
      "operate only in regions with active geysers present",
      "generate electricity for distribution across the grid",
      "use stable shallow ground temperature to heat buildings"
    ],
    correctIndex: 3,
    explanation: "Shallow ground stays near a constant temperature year round anywhere. This makes heat pumps viable far outside volcanic regions."
  },
  {
    id: "6-10-5",
    question: "A key advantage of geothermal electricity over wind and solar is that it",
    options: [
      "provides constant baseload power regardless of weather",
      "requires no drilling or subsurface infrastructure",
      "costs substantially less to develop than any alternative",
      "can be installed in absolutely any geographic location"
    ],
    correctIndex: 0,
    explanation: "High capacity factors make geothermal valuable for grid stability. Its main limitation is geographic, since suitable resources are localized."
  },
  {
    id: "6-10-6",
    question: "Geothermal fluids can cause environmental problems because they often contain",
    options: [
      "pure water requiring no treatment before release",
      "dissolved minerals and gases such as hydrogen sulfide",
      "radioactive isotopes at dangerous concentrations",
      "petroleum hydrocarbons dissolved from source rock"
    ],
    correctIndex: 1,
    explanation: "Hydrogen sulfide produces the rotten egg smell near geothermal fields. Reinjecting spent fluid addresses both disposal and reservoir depletion."
  },
  {
    id: "6-10-7",
    question: "Reinjection of geothermal fluid is practiced primarily to",
    options: [
      "prevent any electricity from being generated onsite",
      "increase the total surface subsidence around the field",
      "maintain reservoir pressure and avoid waste disposal",
      "raise the temperature of the underground reservoir"
    ],
    correctIndex: 2,
    explanation: "Without reinjection, reservoirs deplete and the ground can subside. Injection has occasionally induced small earthquakes, a separate concern."
  },
  {
    id: "6-10-8",
    question: "Enhanced geothermal systems aim to expand geothermal energy by",
    options: [
      "concentrating sunlight onto underground rock formations",
      "extracting heat from the atmosphere rather than the ground",
      "drilling only where natural steam already reaches the surface",
      "fracturing hot dry rock and circulating water through it"
    ],
    correctIndex: 3,
    explanation: "This would make geothermal viable far beyond naturally permeable reservoirs. Induced seismicity has slowed several pilot projects."
  },
  {
    id: "6-10-9",
    question: "Iceland generates a large share of its electricity and heat from geothermal because it",
    options: [
      "sits atop the Mid-Atlantic Ridge with abundant heat",
      "receives more solar radiation than most other countries",
      "imports geothermal fluid from neighboring countries",
      "has almost no other domestic energy resources at all"
    ],
    correctIndex: 0,
    explanation: "Volcanic activity brings heat within easy drilling distance. Iceland also has substantial hydroelectric resources."
  },
  {
    id: "6-10-10",
    question: "Geothermal energy is considered renewable, though a specific field can be depleted if",
    options: [
      "the reservoir is allowed to recharge between extractions",
      "heat is extracted faster than it is replenished",
      "spent fluid is reinjected into the same formation",
      "generation is limited to well below the field's capacity"
    ],
    correctIndex: 1,
    explanation: "Overdrawing a reservoir lowers temperature and pressure over time. Careful management keeps extraction within the field's sustainable rate."
  }
];
